import DashboardLayout from "@/components/DashboardLayout";
import PartnerOnly from "@/components/PartnerOnly";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { getEdvRolePolicy, type EdvRole } from "../../../shared/rbac";
import { ArrowRight, BarChart3, BriefcaseBusiness, Check, ChevronRight, FileCheck2, FileText, Landmark, LockKeyhole, Settings2, ShieldCheck, UsersRound } from "lucide-react";
import { useMemo, useState } from "react";
import { Link } from "wouter";

export default function RoleDashboard() {
  const [role, setRole] = useState<EdvRole>("partner");
  const policy = useMemo(() => getEdvRolePolicy(role), [role]);
  const isPartner = role === "partner";
  const accessCards = isPartner ? [
    { title: "Aprobaciones HITL", description: "7 decisiones esperan criterio profesional.", icon: FileCheck2, href: "/aprobaciones", tone: "bg-rose-50 text-rose-700", action: "Revisar cola" },
    { title: "Órganos operativos", description: "21 células y sus señales de actividad.", icon: UsersRound, href: "/organos", tone: "bg-blue-50 text-blue-700", action: "Ver red" },
    { title: "Banca y conciliación", description: "Cuentas, cobros y movimientos pendientes.", icon: Landmark, href: "/banca", tone: "bg-emerald-50 text-emerald-700", action: "Gestionar banca" },
  ] : [
    { title: "Reportes de mi empresa", description: "IVA, sueldos y rentabilidad compartidos.", icon: BarChart3, href: "/", tone: "bg-blue-50 text-blue-700", action: "Ver reportes" },
    { title: "Facturas", description: "Estado de comprobantes y honorarios.", icon: FileText, href: "/maestros", tone: "bg-violet-50 text-violet-700", action: "Consultar" },
    { title: "Documentos compartidos", description: "Balances y certificados publicados por EDV.", icon: FileCheck2, href: "/aprobaciones", tone: "bg-amber-50 text-amber-700", action: "Abrir documentos" },
  ];

  return <DashboardLayout><PartnerOnly><main className="min-h-screen bg-background px-6 py-8 lg:px-10"><div className="mx-auto max-w-7xl space-y-8">
    <header className="flex flex-col gap-5 border-b border-border/60 pb-7 lg:flex-row lg:items-end lg:justify-between"><div><div className="mb-3 flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.24em] text-primary"><span className="h-2 w-2 rounded-full bg-emerald-500" />EDV · Control de acceso</div><h1 className="text-4xl font-semibold tracking-tight">Panel adaptado a tu rol</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-muted-foreground">La experiencia cambia según el nivel de responsabilidad: el Socio controla la operación completa; el Cliente accede únicamente a la información de su empresa.</p></div><Badge variant="outline" className="w-fit gap-2 border-amber-200 bg-amber-50 text-amber-800"><LockKeyhole className="h-3.5 w-3.5" />Vista de demostración RBAC</Badge></header>

    <section className="grid gap-5 lg:grid-cols-[1fr_1.35fr]"><Card className="border-primary/20 shadow-sm"><CardHeader><CardTitle className="text-base">Simular perfil</CardTitle><p className="text-sm text-muted-foreground">En producción se resuelve desde la sesión y las políticas del servidor.</p></CardHeader><CardContent className="space-y-3"><button onClick={() => setRole("partner")} className={`flex w-full items-center gap-3 rounded-xl border p-4 text-left transition-colors ${isPartner ? "border-primary bg-primary/[0.05] ring-2 ring-primary/15" : "border-border hover:bg-muted/30"}`}><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-slate-900 text-white"><BriefcaseBusiness className="h-5 w-5" /></span><span className="min-w-0 flex-1"><span className="block text-sm font-semibold">Socio / CPN</span><span className="mt-1 block text-xs text-muted-foreground">Dirección, auditoría, aprobación y firma</span></span>{isPartner ? <Check className="h-4 w-4 text-primary" /> : null}</button><button onClick={() => setRole("client")} className={`flex w-full items-center gap-3 rounded-xl border p-4 text-left transition-colors ${!isPartner ? "border-primary bg-primary/[0.05] ring-2 ring-primary/15" : "border-border hover:bg-muted/30"}`}><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-blue-600 text-white"><UsersRound className="h-5 w-5" /></span><span className="min-w-0 flex-1"><span className="block text-sm font-semibold">Cliente final</span><span className="mt-1 block text-xs text-muted-foreground">Consulta de reportes y documentos propios</span></span>{!isPartner ? <Check className="h-4 w-4 text-primary" /> : null}</button></CardContent></Card>
      <Card className="overflow-hidden border-border/70 shadow-sm"><CardContent className="p-0"><div className={`p-6 ${isPartner ? "bg-slate-900 text-white" : "bg-blue-600 text-white"}`}><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-white/60">Sesión actual</p><h2 className="mt-2 text-2xl font-semibold">{policy.label}</h2><p className="mt-2 text-sm text-white/75">{policy.description}</p></div><ShieldCheck className="h-7 w-7 text-white/80" /></div></div><div className="grid grid-cols-2 gap-px bg-border sm:grid-cols-4"><Permission label="Aprobar" allowed={policy.canApprove} /><Permission label="Firmar" allowed={policy.canSign} /><Permission label="Ver clientes" allowed={policy.canViewAllClients} /><Permission label="Gestionar banca" allowed={policy.canManageBanking} /></div></CardContent></Card></section>

    <section><div className="mb-4 flex items-end justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-muted-foreground">Accesos disponibles</p><h2 className="mt-1 text-xl font-semibold">Menú de {isPartner ? "dirección" : "tu empresa"}</h2></div><Badge variant="secondary">{policy.menu.length} módulos</Badge></div><div className="grid gap-4 md:grid-cols-3">{accessCards.map(card => { const Icon = card.icon; return <Card key={card.title} className="group border-border/70 shadow-sm transition-all hover:-translate-y-0.5 hover:shadow-md"><CardContent className="p-5"><div className="flex items-start justify-between"><div className={`rounded-xl p-3 ${card.tone}`}><Icon className="h-5 w-5" /></div><ChevronRight className="h-4 w-4 text-muted-foreground transition-transform group-hover:translate-x-1" /></div><h3 className="mt-5 font-semibold">{card.title}</h3><p className="mt-2 min-h-10 text-sm leading-5 text-muted-foreground">{card.description}</p><Link href={card.href} className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-primary hover:underline">{card.action}<ArrowRight className="h-4 w-4" /></Link></CardContent></Card>; })}</div></section>

    <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Settings2 className="h-4 w-4 text-primary" />Menú visible en esta sesión</CardTitle></CardHeader><CardContent className="flex flex-wrap gap-2">{policy.menu.map(item => <Badge key={item} variant="outline" className="px-3 py-1.5 font-normal">{item}</Badge>)}</CardContent></Card>
  </div></main></PartnerOnly></DashboardLayout>;
}

function Permission({ label, allowed }: { label: string; allowed: boolean }) { return <div className="bg-background p-4 text-center"><p className="text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">{label}</p><p className={`mt-1 text-sm font-semibold ${allowed ? "text-emerald-600" : "text-muted-foreground"}`}>{allowed ? "Permitido" : "Solo lectura"}</p></div>; }
